//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsREDT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nsREDT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again.
        /// </summary>
        internal static string btn_scan_again {
            get {
                return ResourceManager.GetString("btn_scan_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.config.
        /// </summary>
        internal static string config_file {
            get {
                return ResourceManager.GetString("config_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string delete_readonly {
            get {
                return ResourceManager.GetString("delete_readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleted {
            get {
                object obj = ResourceManager.GetObject("deleted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string dont_scan_hidden_folders {
            get {
                return ResourceManager.GetString("dont_scan_hidden_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory you picked is not a folder or does not exist!.
        /// </summary>
        internal static string error_dir_does_not_exist {
            get {
                return ResourceManager.GetString("error_dir_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore file settings are in a bad format!.
        /// </summary>
        internal static string error_ignore_settings {
            get {
                return ResourceManager.GetString("error_ignore_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one folder can be accepted..
        /// </summary>
        internal static string error_only_one_folder {
            get {
                return ResourceManager.GetString("error_only_one_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_hidden {
            get {
                object obj = ResourceManager.GetObject("folder_hidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_hidden_trash_files {
            get {
                object obj = ResourceManager.GetObject("folder_hidden_trash_files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_lock {
            get {
                object obj = ResourceManager.GetObject("folder_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_lock_trash {
            get {
                object obj = ResourceManager.GetObject("folder_lock_trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_readonly {
            get {
                object obj = ResourceManager.GetObject("folder_readonly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_readonly_trash {
            get {
                object obj = ResourceManager.GetObject("folder_readonly_trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_trash_files {
            get {
                object obj = ResourceManager.GetObject("folder_trash_files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_warning {
            get {
                object obj = ResourceManager.GetObject("folder_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0:N0} empty folders (checked {1:N0} folders).
        /// </summary>
        internal static string found_x_empty_folders {
            get {
                return ResourceManager.GetString("found_x_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains trash.
        /// </summary>
        internal static string icon_contains_trash {
            get {
                return ResourceManager.GetString("icon_contains_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default folder.
        /// </summary>
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted folder.
        /// </summary>
        internal static string icon_deleted_folder {
            get {
                return ResourceManager.GetString("icon_deleted_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden folder.
        /// </summary>
        internal static string icon_hidden_folder {
            get {
                return ResourceManager.GetString("icon_hidden_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden trash.
        /// </summary>
        internal static string icon_hidden_trash {
            get {
                return ResourceManager.GetString("icon_hidden_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked folder.
        /// </summary>
        internal static string icon_locked_folder {
            get {
                return ResourceManager.GetString("icon_locked_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked trash.
        /// </summary>
        internal static string icon_locked_trash {
            get {
                return ResourceManager.GetString("icon_locked_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected folder.
        /// </summary>
        internal static string icon_protected_folder {
            get {
                return ResourceManager.GetString("icon_protected_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly folder.
        /// </summary>
        internal static string icon_readonly_folder {
            get {
                return ResourceManager.GetString("icon_readonly_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly trash.
        /// </summary>
        internal static string icon_readonly_trash {
            get {
                return ResourceManager.GetString("icon_readonly_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Folder.
        /// </summary>
        internal static string icon_root {
            get {
                return ResourceManager.GetString("icon_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete.
        /// </summary>
        internal static string icon_warning {
            get {
                return ResourceManager.GetString("icon_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string ignore_0kb_files {
            get {
                return ResourceManager.GetString("ignore_0kb_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*.tmp$/\r\ndesktop.ini\r\nThumbs.db.
        /// </summary>
        internal static string ignore_files {
            get {
                return ResourceManager.GetString("ignore_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Volume Information\r\nRECYCLER\r\nPapierkorb\r\nRecycled\r\nNtUninstall\n$RECYCLE.BIN\nGAC_MSIL.
        /// </summary>
        internal static string ignore_folders {
            get {
                return ResourceManager.GetString("ignore_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string keep_system_folders {
            get {
                return ResourceManager.GetString("keep_system_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log {
            get {
                object obj = ResourceManager.GetObject("log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string log_file {
            get {
                return ResourceManager.GetString("log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string max_depth {
            get {
                return ResourceManager.GetString("max_depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        internal static string max_folders {
            get {
                return ResourceManager.GetString("max_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string pause_between {
            get {
                return ResourceManager.GetString("pause_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder that you want to be cleaned.
        /// </summary>
        internal static string please_select {
            get {
                return ResourceManager.GetString("please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process cancelled!.
        /// </summary>
        internal static string process_cancelled {
            get {
                return ResourceManager.GetString("process_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RED deleted {0:N0} directories for you!.
        /// </summary>
        internal static string red_deleted {
            get {
                return ResourceManager.GetString("red_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon REDt {
            get {
                object obj = ResourceManager.GetObject("REDt", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redt_bg {
            get {
                object obj = ResourceManager.GetObject("redt_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty dirs.
        /// </summary>
        internal static string registry_name {
            get {
                return ResourceManager.GetString("registry_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing empty folders....
        /// </summary>
        internal static string rem_empty_folders {
            get {
                return ResourceManager.GetString("rem_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing empty folders ({0:N0}/{1:N0})....
        /// </summary>
        internal static string removing_empty_folders {
            get {
                return ResourceManager.GetString("removing_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning folders....
        /// </summary>
        internal static string scanning_folders {
            get {
                return ResourceManager.GetString("scanning_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching empty folders....
        /// </summary>
        internal static string searching_empty_folders {
            get {
                return ResourceManager.GetString("searching_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\.
        /// </summary>
        internal static string start_folder {
            get {
                return ResourceManager.GetString("start_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, do you really want to delete empty system folders?\nThis may harm your operating system..
        /// </summary>
        internal static string warning_really_delete {
            get {
                return ResourceManager.GetString("warning_really_delete", resourceCulture);
            }
        }
    }
}
